package examples
package main

import (
	"log"
	"net/http"


















































































































































































































































}	log.Println(`  -d '{"organization_id": 1}'`)	log.Println(`  -H "Content-Type: application/json" \`)	log.Println(`curl -X POST http://localhost:8080/api/v1/invoice-numbers/generate/next \`)	log.Println("# Generate next invoice number:")	log.Println("")	log.Println(`  -d '{"value": "BILL"}'`)	log.Println(`  -H "Content-Type: application/json" \`)	log.Println(`curl -X PUT http://localhost:8080/api/v1/settings/invoicing/invoice_prefix \`)	log.Println("# Update invoice prefix:")	log.Println("")	log.Println("curl http://localhost:8080/api/v1/settings/invoicing")	log.Println("# Get invoice settings:")	log.Println("")	log.Println("curl http://localhost:8080/api/v1/settings")	log.Println("# Get all settings:")	log.Println("\n🎯 Usage Examples:")func demonstrateUsage() {// Example usage after startup}	return names	}		names = append(names, name)	for name := range schemas {	names := make([]string, 0, len(schemas))func getModuleNames(schemas map[string]entities.ModuleSettingsSchema) []string {}	}		c.Next()		}			return			c.AbortWithStatus(http.StatusNoContent)		if c.Request.Method == "OPTIONS" {		c.Header("Access-Control-Allow-Headers", "Content-Type, Authorization, X-Tenant-ID, X-Organization-ID")		c.Header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")		c.Header("Access-Control-Allow-Origin", "*")	return func(c *gin.Context) {func corsMiddleware() gin.HandlerFunc {}	}		c.Next()		c.Set("organization_id", organizationID)		c.Set("tenant_id", tenantID)		}			// Parse organization ID from header		if orgHeader := c.GetHeader("X-Organization-ID"); orgHeader != "" {				}			// Parse tenant ID from header		if tenantHeader := c.GetHeader("X-Tenant-ID"); tenantHeader != "" {		// Try headers first				organizationID := uint(1)		tenantID := uint(1)		// In production, extract from JWT token or authentication	return func(c *gin.Context) {func tenantOrgMiddleware() gin.HandlerFunc {}	return router	})		})			"settings": settings,			"message":  "Current invoice settings",		c.JSON(http.StatusOK, gin.H{		}			return			c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})		if err != nil {		settings, err := invoiceService.GetInvoiceSettings(c.Request.Context(), tenantID, organizationID)				organizationID := uint(1)		tenantID := uint(1)	router.GET("/demo/invoice-settings", func(c *gin.Context) {	// Demo endpoints	})		})			"schemas":           schemas,			"modules":           getModuleNames(schemas),			"registered_modules": len(schemas),			"message":           "Advanced Settings System",		c.JSON(http.StatusOK, gin.H{		schemas := settingsManager.GetRegistryInfo()	router.GET("/info/settings", func(c *gin.Context) {	// Settings system info	})		})			"version": "1.0.0",			"service": "ae-backend-with-settings",			"status":  "healthy",		c.JSON(http.StatusOK, gin.H{	router.GET("/health", func(c *gin.Context) {	// Health check	}		invoiceNumbers.POST("/generate/next", invoiceNumHandler.GenerateNextInvoiceNumber)		invoiceNumbers.POST("/generate", invoiceNumHandler.GenerateInvoiceNumber)	{	invoiceNumbers := api.Group("/invoice-numbers")	invoiceNumHandler := invoiceNumberHandler.NewInvoiceNumberHandler(invoiceNumberSvc, settingsManager, nil)	// Invoice number routes	settingsHandler.RegisterRoutes(api)	settingsHandler := handlers.NewSettingsHandler(settingsManager)	// Settings routes	api := router.Group("/api/v1")	// API group	router.Use(corsMiddleware())	router.Use(tenantOrgMiddleware())	// Add middleware	router := gin.Default()func setupRouter(settingsManager *manager.SettingsManager, invoiceService *services.InvoiceService, invoiceNumberSvc *invoiceNumberService.InvoiceNumberService) *gin.Engine {}	return nil	// }	//     return err	// if err := settingsManager.RegisterModule(companyProvider, tenantID, organizationID); err != nil {	// companyProvider := company.NewCompanySettingsProvider()	// Example:	// Register additional modules here as they're created	log.Println("✅ Invoice settings module registered")	}		return err	if err := settingsManager.RegisterModule(invoiceProvider, tenantID, organizationID); err != nil {	invoiceProvider := invoice.NewInvoiceSettingsProvider()	// Register invoice module	organizationID := uint(1)	tenantID := uint(1)	// Example tenant and organization - in production these would be dynamic		log.Println("📝 Registering settings modules...")func registerSettingsModules(settingsManager *manager.SettingsManager) error {}	return nil	log.Println("✅ Database migrations completed")	}		}			return err		if err := db.Exec(indexSQL).Error; err != nil {	for _, indexSQL := range indexes {	}		`CREATE INDEX IF NOT EXISTS idx_settings_updated_at ON settings(updated_at)`,		`CREATE INDEX IF NOT EXISTS idx_settings_tenant_org_domain_key ON settings(tenant_id, organization_id, domain, key)`,		`CREATE INDEX IF NOT EXISTS idx_settings_tenant_org_domain ON settings(tenant_id, organization_id, domain)`,	indexes := []string{	// Create performance indexes	}		return err	if err := db.AutoMigrate(&entities.Setting{}); err != nil {	// Auto-migrate settings table		log.Println("🔄 Running database migrations...")func runMigrations(db *gorm.DB) error {}	return db, nil	log.Println("✅ Database connected successfully")	}		return nil, err	if err != nil {	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})		dsn := "host=localhost user=ae_user password=ae_password dbname=ae_backend port=5432 sslmode=disable"	// Replace with your actual database connection stringfunc initDatabase() (*gorm.DB, error) {}	}		log.Fatal("Server failed to start:", err)	if err := http.ListenAndServe(":8080", router); err != nil {	log.Println("📊 Settings info available at http://localhost:8080/info/settings")	log.Println("📄 Invoice number API available at http://localhost:8080/api/v1/invoice-numbers")	log.Println("📋 Settings API available at http://localhost:8080/api/v1/settings")	log.Println("🚀 Server starting on :8080")	router := setupRouter(settingsManager, invoiceService, invoiceNumberSvc)	// Setup HTTP server	invoiceNumberSvc := invoiceNumberService.NewInvoiceNumberService(db, settingsManager)	invoiceService := services.NewInvoiceService(db, settingsManager)	// Initialize services with settings integration	}		log.Fatal("Failed to register settings modules:", err)	if err := registerSettingsModules(settingsManager); err != nil {	// Register settings modules	settingsManager := manager.NewSettingsManager(settingsRepo)	settingsRepo := repositories.NewGORMSettingsRepository(db)	// Initialize settings system	}		log.Fatal("Failed to run migrations:", err)	if err := runMigrations(db); err != nil {	// Run migrations	}		log.Fatal("Failed to initialize database:", err)	if err != nil {	db, err := initDatabase()	// Initialize databasefunc main() {)	invoiceNumberHandler "github.com/ae-base-server/modules/invoice_number/handlers"	invoiceNumberService "github.com/ae-base-server/modules/invoice_number/services"	"github.com/ae-base-server/modules/invoice/services"	"github.com/ae-base-server/modules/invoice/settings"	// Invoice module integration		"github.com/ae-base-server/pkg/settings/repositories"	"github.com/ae-base-server/pkg/settings/manager"	"github.com/ae-base-server/pkg/settings/handlers"	"github.com/ae-base-server/pkg/settings/entities"	// Settings system	"gorm.io/gorm"	"gorm.io/driver/postgres"	"github.com/gin-gonic/gin"