package integration
package integration

import (
	"fmt"
	





































































































































































}	}		Localization: NewLocalizationSettingsProvider(db),		Company:      NewCompanySettingsProvider(db),		Billing:      NewBillingSettingsProvider(db),		Invoice:      NewInvoiceSettingsProvider(db),	return &SettingsProviderRegistry{func NewSettingsProviderRegistry(db *gorm.DB) *SettingsProviderRegistry {// NewSettingsProviderRegistry creates a new settings provider registry}	Localization  *LocalizationSettingsProvider	Company       *CompanySettingsProvider	Billing       *BillingSettingsProvider	Invoice       *InvoiceSettingsProvidertype SettingsProviderRegistry struct {// SettingsProviderRegistry holds all settings providers for easy dependency injection}	return settings.DateFormat, settings.TimeFormat, settings.AmountFormat, settings.Locale, nil	}		return "", "", "", "", fmt.Errorf("failed to get formats: %w", err)	if err != nil {	settings, err := p.settingsService.GetLocalizationSettings(tenantID)func (p *LocalizationSettingsProvider) GetFormats(tenantID uint) (string, string, string, string, error) {// GetFormats returns date, time, and amount formatting preferences}	}		settingsService: services.NewSettingsService(db),	return &LocalizationSettingsProvider{func NewLocalizationSettingsProvider(db *gorm.DB) *LocalizationSettingsProvider {// NewLocalizationSettingsProvider creates a new localization settings provider}	settingsService *services.SettingsServicetype LocalizationSettingsProvider struct {// LocalizationSettingsProvider provides localization settings}		   settings.BankAccountBIC, settings.BankAccountIBAN, nil	return settings.BankAccountOwner, settings.BankAccountBank, 	}		return "", "", "", "", fmt.Errorf("failed to get bank details: %w", err)	if err != nil {	settings, err := p.settingsService.GetCompanySettings(tenantID)func (p *CompanySettingsProvider) GetBankDetails(tenantID uint) (string, string, string, string, error) {// GetBankDetails returns bank account information}	return p.settingsService.GetCompanySettings(tenantID)func (p *CompanySettingsProvider) GetCompanyInfo(tenantID uint) (*entities.CompanySettings, error) {// GetCompanyInfo returns basic company information}	}		settingsService: services.NewSettingsService(db),	return &CompanySettingsProvider{func NewCompanySettingsProvider(db *gorm.DB) *CompanySettingsProvider {// NewCompanySettingsProvider creates a new company settings provider}	settingsService *services.SettingsServicetype CompanySettingsProvider struct {// CompanySettingsProvider provides company information}	return settings.LineItemSingleUnitText, settings.LineItemDoubleUnitText, nil	}		return "", "", fmt.Errorf("failed to get line item texts: %w", err)	if err != nil {	settings, err := p.settingsService.GetBillingSettings(tenantID)func (p *BillingSettingsProvider) GetLineItemTexts(tenantID uint) (string, string, error) {// GetLineItemTexts returns the line item texts for single/double units}	return settings.TaxRate, nil	}		return 0, fmt.Errorf("failed to get tax rate: %w", err)	if err != nil {	settings, err := p.settingsService.GetBillingSettings(tenantID)func (p *BillingSettingsProvider) GetTaxRate(tenantID uint) (float64, error) {// GetTaxRate returns the tax rate for billing}	return settings.UnitPrice, nil	}		return 0, fmt.Errorf("failed to get unit price: %w", err)	if err != nil {	settings, err := p.settingsService.GetBillingSettings(tenantID)func (p *BillingSettingsProvider) GetUnitPrice(tenantID uint) (float64, error) {// GetUnitPrice returns the default unit price}	return settings.Mode, settings.Config, nil	}		return "", nil, fmt.Errorf("failed to get billing mode: %w", err)	if err != nil {	settings, err := p.settingsService.GetBillingSettings(tenantID)func (p *BillingSettingsProvider) GetBillingMode(tenantID uint) (string, map[string]interface{}, error) {// GetBillingMode returns the billing mode for extra efforts}	}		settingsService: services.NewSettingsService(db),	return &BillingSettingsProvider{func NewBillingSettingsProvider(db *gorm.DB) *BillingSettingsProvider {// NewBillingSettingsProvider creates a new billing settings provider}	settingsService *services.SettingsServicetype BillingSettingsProvider struct {// BillingSettingsProvider provides billing-related settings}	return settings.PaymentDueDays, settings.FirstReminderDays, settings.SecondReminderDays, nil	}		return 0, 0, 0, fmt.Errorf("failed to get payment terms: %w", err)	if err != nil {	settings, err := p.settingsService.GetInvoicingSettings(tenantID)func (p *InvoiceSettingsProvider) GetPaymentTerms(tenantID uint) (int, int, int, error) {// GetPaymentTerms returns payment terms configuration}	return settings.NumberFormat, settings.NumberPrefix, nil	}		return "", "", fmt.Errorf("failed to get invoice number config: %w", err)	if err != nil {	settings, err := p.settingsService.GetInvoicingSettings(tenantID)func (p *InvoiceSettingsProvider) GetInvoiceNumberConfig(tenantID uint) (string, string, error) {// GetInvoiceNumberConfig returns invoice numbering configuration}	return settings.DefaultVATExempt, settings.VATExemptionText, nil	}		return false, "", fmt.Errorf("failed to get VAT exempt status: %w", err)	if err != nil {	settings, err := p.settingsService.GetInvoicingSettings(tenantID)func (p *InvoiceSettingsProvider) GetVATExemptStatus(tenantID uint) (bool, string, error) {// GetVATExemptStatus returns the default VAT exemption status}	return settings.DefaultVATRate, nil	}		return 0, fmt.Errorf("failed to get VAT rate: %w", err)	if err != nil {	settings, err := p.settingsService.GetInvoicingSettings(tenantID)func (p *InvoiceSettingsProvider) GetVATRate(tenantID uint) (float64, error) {// GetVATRate returns the default VAT rate for a tenant}	}		settingsService: services.NewSettingsService(db),	return &InvoiceSettingsProvider{func NewInvoiceSettingsProvider(db *gorm.DB) *InvoiceSettingsProvider {// NewInvoiceSettingsProvider creates a new invoice settings provider}	settingsService *services.SettingsServicetype InvoiceSettingsProvider struct {// InvoiceSettingsProvider provides invoice-related settings)	"gorm.io/gorm"	"github.com/ae-base-server/pkg/settings/services"	"github.com/ae-base-server/pkg/settings/entities"