package handlers
package handlers

import (





























































































































































































































































































































}	return 1 // Default tenant ID - should be handled better in production		}		}			return uint(tid)		if tid, err := strconv.ParseUint(tidStr, 10, 32); err == nil {	if tidStr := c.Query("tenant_id"); tidStr != "" {	// Fallback to query param		}		}			return tid		if tid, ok := tenantID.(uint); ok {	if tenantID, exists := c.Get("tenantID"); exists {func getTenantID(c *gin.Context) uint {// Helper function to get tenant ID from context}	})		"message": "Billing settings updated successfully",		"success": true,	c.JSON(http.StatusOK, gin.H{	}		return		})			"error":   err.Error(),			"message": "Failed to update billing settings",			"success": false,		c.JSON(http.StatusInternalServerError, gin.H{	if err := h.settingsService.SetBillingSettings(tenantID, settings); err != nil {	}		return		})			"error":   err.Error(),			"message": "Invalid billing settings data",			"success": false,		c.JSON(http.StatusBadRequest, gin.H{	if err := c.ShouldBindJSON(&settings); err != nil {	var settings entities.BillingSettings	tenantID := getTenantID(c)func (h *SettingsHandler) UpdateBillingSettings(c *gin.Context) {// @Router /settings/billing [put]// @Failure 500 {object} map[string]interface{}// @Failure 400 {object} map[string]interface{}// @Success 200 {object} map[string]interface{}// @Param settings body entities.BillingSettings true "Billing settings"// @Produce json// @Accept json// @Tags settings// @Description Update billing-specific configuration settings// @Summary Update billing settings// UpdateBillingSettings godoc}	})		"data":    settings,		"message": "Billing settings retrieved successfully",		"success": true,	c.JSON(http.StatusOK, gin.H{	}		return		})			"error":   err.Error(),			"message": "Failed to retrieve billing settings",			"success": false,		c.JSON(http.StatusInternalServerError, gin.H{	if err != nil {	settings, err := h.settingsService.GetBillingSettings(tenantID)	tenantID := getTenantID(c)func (h *SettingsHandler) GetBillingSettings(c *gin.Context) {// @Router /settings/billing [get]// @Failure 500 {object} map[string]interface{}// @Success 200 {object} entities.BillingSettings// @Produce json// @Accept json// @Tags settings// @Description Retrieve billing-specific configuration settings// @Summary Get billing settings// GetBillingSettings godoc}	})		"message": "Invoicing settings updated successfully",		"success": true,	c.JSON(http.StatusOK, gin.H{	}		return		})			"error":   err.Error(),			"message": "Failed to update invoicing settings",			"success": false,		c.JSON(http.StatusInternalServerError, gin.H{	if err := h.settingsService.SetInvoicingSettings(tenantID, settings); err != nil {	}		return		})			"error":   err.Error(),			"message": "Invalid invoicing settings data",			"success": false,		c.JSON(http.StatusBadRequest, gin.H{	if err := c.ShouldBindJSON(&settings); err != nil {	var settings entities.InvoicingSettings	tenantID := getTenantID(c)func (h *SettingsHandler) UpdateInvoicingSettings(c *gin.Context) {// @Router /settings/invoicing [put]// @Failure 500 {object} map[string]interface{}// @Failure 400 {object} map[string]interface{}// @Success 200 {object} map[string]interface{}// @Param settings body entities.InvoicingSettings true "Invoicing settings"// @Produce json// @Accept json// @Tags settings// @Description Update invoice-specific configuration settings// @Summary Update invoicing settings// UpdateInvoicingSettings godoc}	})		"data":    settings,		"message": "Invoicing settings retrieved successfully",		"success": true,	c.JSON(http.StatusOK, gin.H{	}		return		})			"error":   err.Error(),			"message": "Failed to retrieve invoicing settings",			"success": false,		c.JSON(http.StatusInternalServerError, gin.H{	if err != nil {	settings, err := h.settingsService.GetInvoicingSettings(tenantID)	tenantID := getTenantID(c)func (h *SettingsHandler) GetInvoicingSettings(c *gin.Context) {// @Router /settings/invoicing [get]// @Failure 500 {object} map[string]interface{}// @Success 200 {object} entities.InvoicingSettings// @Produce json// @Accept json// @Tags settings// @Description Retrieve invoice-specific configuration settings// @Summary Get invoicing settings// GetInvoicingSettings godoc}	})		"message": "Company settings updated successfully",		"success": true,	c.JSON(http.StatusOK, gin.H{	}		return		})			"error":   err.Error(),			"message": "Failed to update company settings",			"success": false,		c.JSON(http.StatusInternalServerError, gin.H{	if err := h.settingsService.SetCompanySettings(tenantID, settings); err != nil {	}		return		})			"error":   err.Error(),			"message": "Invalid company settings data",			"success": false,		c.JSON(http.StatusBadRequest, gin.H{	if err := c.ShouldBindJSON(&settings); err != nil {	var settings entities.CompanySettings	tenantID := getTenantID(c)func (h *SettingsHandler) UpdateCompanySettings(c *gin.Context) {// @Router /settings/company [put]// @Failure 500 {object} map[string]interface{}// @Failure 400 {object} map[string]interface{}// @Success 200 {object} map[string]interface{}// @Param settings body entities.CompanySettings true "Company settings"// @Produce json// @Accept json// @Tags settings// @Description Update company/organization information settings// @Summary Update company settings// UpdateCompanySettings godoc}	})		"data":    settings,		"message": "Company settings retrieved successfully",		"success": true,	c.JSON(http.StatusOK, gin.H{	}		return		})			"error":   err.Error(),			"message": "Failed to retrieve company settings",			"success": false,		c.JSON(http.StatusInternalServerError, gin.H{	if err != nil {	settings, err := h.settingsService.GetCompanySettings(tenantID)	tenantID := getTenantID(c)func (h *SettingsHandler) GetCompanySettings(c *gin.Context) {// @Router /settings/company [get]// @Failure 500 {object} map[string]interface{}// @Success 200 {object} entities.CompanySettings// @Produce json// @Accept json// @Tags settings// @Description Retrieve company/organization information settings// @Summary Get company settings// GetCompanySettings godoc}	})		"message": "Settings updated successfully",		"success": true,	c.JSON(http.StatusOK, gin.H{	}		}			return			})				"error":   err.Error(),				"message": "Failed to update setting",				"success": false,			c.JSON(http.StatusInternalServerError, gin.H{		if err := h.settingsService.SetSetting(tenantID, domain, key, value); err != nil {	for key, value := range settingsData {	// Set each setting individually	}		return		})			"error":   err.Error(),			"message": "Invalid request data",			"success": false,		c.JSON(http.StatusBadRequest, gin.H{	if err := c.ShouldBindJSON(&settingsData); err != nil {	var settingsData map[string]interface{}	tenantID := getTenantID(c)	domain := entities.SettingsDomain(c.Param("domain"))func (h *SettingsHandler) UpdateDomainSettings(c *gin.Context) {// @Router /settings/{domain} [put]// @Failure 500 {object} map[string]interface{}// @Failure 400 {object} map[string]interface{}// @Success 200 {object} map[string]interface{}// @Param settings body map[string]interface{} true "Settings to update"// @Param domain path string true "Settings domain" Enums(company,invoicing,billing,localization,booking,notification,integration)// @Produce json// @Accept json// @Tags settings// @Description Update all settings for a specific domain// @Summary Update settings for a domain// UpdateDomainSettings godoc}	})		"data":    settings,		"message": "Settings retrieved successfully", 		"success": true,	c.JSON(http.StatusOK, gin.H{	}		return		})			"error":   err.Error(),			"message": "Failed to retrieve settings",			"success": false,		c.JSON(http.StatusInternalServerError, gin.H{	if err != nil {	settings, err := h.settingsService.GetDomainSettings(tenantID, domain)	tenantID := getTenantID(c)	domain := entities.SettingsDomain(c.Param("domain"))func (h *SettingsHandler) GetDomainSettings(c *gin.Context) {// @Router /settings/{domain} [get]// @Failure 500 {object} map[string]interface{}// @Failure 400 {object} map[string]interface{}// @Success 200 {object} map[string]interface{}// @Param domain path string true "Settings domain" Enums(company,invoicing,billing,localization,booking,notification,integration)// @Produce json// @Accept json// @Tags settings// @Description Retrieve all settings for a specific domain (company, invoicing, billing, etc.)// @Summary Get all settings for a domain// GetDomainSettings godoc}	}		settingsService: services.NewSettingsService(db),	return &SettingsHandler{func NewSettingsHandler(db *gorm.DB) *SettingsHandler {// NewSettingsHandler creates a new settings handler}	settingsService *services.SettingsServicetype SettingsHandler struct {// SettingsHandler handles settings-related HTTP requests)	"gorm.io/gorm"	"github.com/gin-gonic/gin"	"github.com/ae-base-server/pkg/settings/services"	"github.com/ae-base-server/pkg/settings/entities"	"strconv"	"net/http"